### ISSUE TITLE
onorientationchange not working correctly

### ISSUE THREAD

**Issue by Strydom** [davatron5000/FitText.js#134]
Hi,
I seem to be having a problem on mobile devices when the orientation is changed.

Say it's portrait, the text is smaller and then I turn the phone around to landscape the text should enlarge but instead it stays the same size. When I then turn the phone back around to portrait the text enlarges.

It's as if the script is behind an orientation so it thinks landscape is portrait and vice versa or it just doesn't register the first time.

**Comment by TrentWalton** [comment]
Hiya! Could you maybe throw together an isolated test case on codepen?

**Comment by Strydom** [comment]
I have set up the code pen but I haven't used it before and couldn't get your plugin to work with it, maybe you could give it a go?

http://codepen.io/anon/pen/YXwPag

**Comment by davatron5000** [comment]
Forked and updated your pen, tested in iOS Simulator got it working as expected: http://codepen.io/davatron5000/full/EjPKGq

I had to do two things:

- Changed FitText `<script>` tag to use CDNjs.com instead of linking to Github, Github blocks hotlinking. In the console errors like `$.fn.fitText() is undefined` was my clue there.
- Add the proper `<meta name="viewport" content="width=device-width, initial-scale=1">` required by Apple to make orientation changes behave correctly.
