### ISSUE TITLE
Problem with scrollReveal.js

### ISSUE THREAD

**Issue by nikmauro** [davatron5000/FitText.js#144]
hello i have problem with FitText.js library, when enable the scrollReveal.js the fittext resize stop working.
Any tip about this?

**Comment by nikmauro** [comment]
here a [jsbin](http://jsbin.com/guhopu/edit?html,output)

**Comment by CosmicWebServices** [comment]
It is working for me with the latest Chrome OS? What browser/OS are you on?

**Comment by davatron5000** [comment]
http://jsbin.com/zuqijebopi/1/edit?html,output

If you run FitText before ScrollReveal it'll work. ScrollReveal hides the element you're trying to FitText, which means it has nothing to base height/width off of. Therefore it fails.  For this example tho, you may want to use `vw` units instead of FitText.

**Comment by jlmakes** [comment]
:+1:
